### ISSUE TITLE
npm missing release

### ISSUE THREAD

**Issue by ManRueda** [paulcbetts/electron-prebuilt-compile#2]
With the last electron-compile version update, you forgot to update the package.json version and release on NPM. I can't get the last version...

Thanks!!

**Comment by paulcbetts** [comment]
Can you post the npm output?

**Comment by ManRueda** [comment]
Sorry i was on vacations. I can't give you an output now... I'm using my own branch of electron-compile (i sent a PR with the changes, to use NPM in the future).

I will close it for now, and i will check it again when the PR will be merged
