### ISSUE TITLE
Missing dependency in electron-compilers

### ISSUE THREAD

**Issue by riggerthegeek** [paulcbetts/electron-prebuilt-compile#22]
I've found an issue this morning with a missing dependency `@paulcbetts/node-sass` inside `electron-compilers` (see https://github.com/electron/electron-compilers/issues/44 for more detail).

I know this isn't an issue with this package _pe se_, but I notice that this package pulls in the `electron-compilers` package with "*" - would it be worth locking down the version numbers so this doesn't happen in future?

For the record, I've solved my specific issue with the following `npm-shrinkwrap.json` file:

```json
{
  "name": "NodeDB",
  "version": "0.0.0",
  "dependencies": {
    "electron-compilers": {
      "version": "4.0.7"
    }
  }
}
```

**Comment by paulcbetts** [comment]
This is fixed now, sorry - the package somehow didn't get marked as public
