### ISSUE TITLE
Imported LESS doesn't rebuild each time

### ISSUE THREAD

**Issue by cheshire137** [paulcbetts/electron-prebuilt-compile#9]
I'm having trouble getting LESS files I import into my main LESS file to rebuild each time. I have `<link rel="stylesheet" type="text/less" href="components/App/App.less">` in my app and within App.less I have several `@import "../Filter/Filter.less";` lines for other LESS in my app. I can change Filter.less and reload my app without the new changes appearing. If I put the LESS directly in App.less, reloading works every time to see the new styling. Putting it in an imported LESS file, I have to reload a few times, change App.less, and generally poke things a bunch to finally get the new styles to work. I'm actually not sure of the exact flow to get imported LESS to take effect, I usually just stumble upon it after I've been working on other parts of the app and reloading periodically.

https://github.com/cheshire137/gh-notifications-snoozer is the app in question I'm working with.

**Comment by mnquintana** [comment]
It looks like you're running into https://github.com/electron/electron-compile/issues/27 – I'm working on a fix in https://github.com/electron/electron-compile/pull/116 and https://github.com/electron/electron-compilers/pull/38 😄
